### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by williambj1** [williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531#2]
- [ ] Check Sound Card path maps & nodes via special Windows drivers.
- [ ] Rewrite & simplify Config.plist
- [ ] Simplify  useless drivers
- [ ] Try OpenCore
- [ ] Update Kexts
